apiVersion: v1
kind: Pod
metadata:
  name: time-app-configmap
  labels:
    name: time-app-configmap
spec:
  containers:
    - name: time-app-configmap
      image: itsgg/sinatra-docker:0.1
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
      env:
        - name: email
          valueFrom:
            configMapKeyRef:
              name: time-app-configmap
              key: email
      ports:
        - containerPort: 8080
