apiVersion: apps/v1
kind: Deployment
metadata:
  name: time-app
spec:
  selector:
    matchLabels:
      app: time-app
  template:
    metadata:
      labels:
        app: time-app
    spec:
      containers:
        - name: time-app
          image: itsgg/sinatra-docker:0.1
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080


            
