apiVersion: v1
kind: Pod
metadata:
  name: time-app-secret
  labels:
    name: time-app-secret
spec:
  containers:
    - name: time-app-secret
      image: itsgg/sinatra-docker:0.1
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
      ports:
        - containerPort: 8080
      volumeMounts:
        - mountPath: /password
          name: test-secret
  volumes:
    - name: test-secret
      secret:
        secretName: test-app
