apiVersion: v1
kind: Pod
metadata:
  name: time-app-volume
  labels:
    name: time-app-volume
spec:
  containers:
  - name: time-app-volume
    image: itsgg/sinatra-docker:0.1
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"        
    ports:
      - containerPort: 8080
    volumeMounts:
      - mountPath: /data
        name: data-volume
  volumes:
    - name: data-volume
      hostPath:
        path: /data
        type: DirectoryOrCreate
